In [ ]:
from huggingface_hub import login
import getpass

token = getpass.getpass("Nhập HuggingFace token: ")
login(token)

# Import dữ liệu

## Data VNExpress

In [ ]:
from datasets import load_dataset
import pandas as pd
import numpy as np

ds = load_dataset("BaoNhan/VNExpress_News_11_Categories")

# Chuyển sang DataFrame
train_df = pd.DataFrame(ds['train'])
test_df  = pd.DataFrame(ds['test'])
val_df=pd.DataFrame(ds['validation'])

print(train_df.columns)

Index(['category', 'date', 'title', 'description', 'text', 'author', 'url'], dtype='object')

## Data DanTri

In [ ]:
from datasets import load_dataset
import pandas as pd
import numpy as np

ds = load_dataset("BaoNhan/DanTri_News_11_Categories")

train_df = pd.DataFrame(ds['train'])

print(train_df.columns)

README.md: 0.00B [00:00, ?B/s]

data_0.parquet:   0%|          | 0.00/97.3M [00:00<?, ?B/s]

data_1.parquet:   0%|          | 0.00/100M [00:00<?, ?B/s]

data_2.parquet:   0%|          | 0.00/110M [00:00<?, ?B/s]

data_3.parquet:   0%|          | 0.00/119M [00:00<?, ?B/s]

data_4.parquet:   0%|          | 0.00/96.5M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Index(['date', 'title', 'description', 'author', 'content', 'url', 'label'], dtype='object')

## Data VietnamNet

In [ ]:
from datasets import load_dataset
import pandas as pd
import numpy as np

ds = load_dataset("BaoNhan/VietNamNet_News_10_Categories")

train_df = pd.DataFrame(ds['train'])

print(train_df.columns)

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00004.parquet:   0%|          | 0.00/193M [00:00<?, ?B/s]

data/train-00001-of-00004.parquet:   0%|          | 0.00/209M [00:00<?, ?B/s]

data/train-00002-of-00004.parquet:   0%|          | 0.00/193M [00:00<?, ?B/s]

data/train-00003-of-00004.parquet:   0%|          | 0.00/191M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Index(['date', 'title', 'description', 'text', 'author', 'url', 'label'], dtype='object')

# EDA

In [ ]:
from datasets import load_dataset
import pandas as pd

# VNExpress
ds1 = load_dataset("BaoNhan/VNExpress_News_11_Categories")
df1 = pd.DataFrame(ds1['train'])
df1_1 = pd.DataFrame(ds1['test'])
df1_2 = pd.DataFrame(ds1['validation'])
df1 = df1.rename(columns={
    "category": "label"
})
df1_1 = df1_1.rename(columns={
    "category": "label"
})
df1 = df1.rename(columns={
    "category": "label"
})
df1_2 = df1_1.rename(columns={
    "category": "label"
})
# DanTri
ds2 = load_dataset("BaoNhan/DanTri_News_11_Categories")
df2 = pd.DataFrame(ds2['train'])
df2 = df2.rename(columns={
    "content": "text"
})
# VietNamNet
ds3 = load_dataset("BaoNhan/VietNamNet_News_10_Categories")
df3 = pd.DataFrame(ds3['train'])

README.md: 0.00B [00:00, ?B/s]

train.parquet:   0%|          | 0.00/671M [00:00<?, ?B/s]

dev.parquet:   0%|          | 0.00/83.8M [00:00<?, ?B/s]

test.parquet:   0%|          | 0.00/84.1M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data_0.parquet:   0%|          | 0.00/97.3M [00:00<?, ?B/s]

data_1.parquet:   0%|          | 0.00/100M [00:00<?, ?B/s]

data_2.parquet:   0%|          | 0.00/110M [00:00<?, ?B/s]

data_3.parquet:   0%|          | 0.00/119M [00:00<?, ?B/s]

data_4.parquet:   0%|          | 0.00/96.5M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00004.parquet:   0%|          | 0.00/193M [00:00<?, ?B/s]

data/train-00001-of-00004.parquet:   0%|          | 0.00/209M [00:00<?, ?B/s]

data/train-00002-of-00004.parquet:   0%|          | 0.00/193M [00:00<?, ?B/s]

data/train-00003-of-00004.parquet:   0%|          | 0.00/191M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
cols = ['date','title','description','text','author','url','label']

df1 = df1[cols]
df1_1 = df1_1[cols]
df1_2 = df1_2[cols]
df2 = df2[cols]
df3 = df3[cols]
# thêm source
df1['source'] = 'VNExpress'
df1_1['source'] = 'VNExpress'
df1_2['source'] = 'VNExpress'

df2['source'] = 'DanTri'
df3['source'] = 'VietNamNet'

In [ ]:
df_all = pd.concat([df1, df2, df3,df1_1,df1_2], ignore_index=True)

print("Total samples:", len(df_all))
print(df_all['label'].value_counts())

print(df_all['source'].value_counts())

Total samples: 1042295
label
6     148125
8     142594
7     132444
3     131746
5     105775
2     103288
4      74145
1      65187
10     58536
9      51363
0      29092
Name: count, dtype: int64
source
VietNamNet    401648
VNExpress     401160
DanTri        239487
Name: count, dtype: int64

In [ ]:
df_all = df_all[df_all['label'] != 0]

In [ ]:
print("Total samples:", len(df_all))
print(df_all['label'].value_counts())

Total samples: 1013203
label
6     148125
8     142594
7     132444
3     131746
5     105775
2     103288
4      74145
1      65187
10     58536
9      51363
Name: count, dtype: int64

# Check Data Quality

In [ ]:
# ===== DATA QUALITY CHECK (KHÔNG THAY ĐỔI DATA) =====

print("Tổng số dòng:", len(df_all))

# 1. Kiểm tra NaN
title_nan = df_all['title'].isna().sum()
text_nan  = df_all['text'].isna().sum()

# 2. Kiểm tra chuỗi rỗng
title_empty = (df_all['title'].astype(str).str.strip() == "").sum()
text_empty  = (df_all['text'].astype(str).str.strip() == "").sum()

# 3. Kiểm tra trùng
title_dup = df_all['title'].duplicated().sum()
text_dup  = df_all['text'].duplicated().sum()

# 4. Trùng cả title + text
both_dup = df_all.duplicated(subset=['title','text']).sum()

# 5. Title = Text
same_content = (df_all['title'] == df_all['text']).sum()

# ===== REPORT =====
print("\n--- Missing values ---")
print("Title NaN:", title_nan)
print("Text NaN :", text_nan)

print("\n--- Empty strings ---")
print("Title rỗng:", title_empty)
print("Text rỗng :", text_empty)

print("\n--- Duplicate ---")
print("Title trùng:", title_dup)
print("Text trùng :", text_dup)
print("Title + Text trùng:", both_dup)

print("\n--- Title = Text ---")
print("Title giống Text:", same_content)

Tổng số dòng: 1013203

--- Missing values ---
Title NaN: 1672
Text NaN : 0

--- Empty strings ---
Title rỗng: 0
Text rỗng : 0

--- Duplicate ---
Title trùng: 49843
Text trùng : 42942
Title + Text trùng: 40989

--- Title = Text ---
Title giống Text: 0

Delete duplicate

In [ ]:
before = len(df_all)

df_all = df_all.drop_duplicates(subset=['title','text'], keep='first').reset_index(drop=True)

after = len(df_all)

print("Trước:", before)
print("Sau :", after)
print("Đã xoá:", before - after)

Trước: 1013203
Sau : 972214
Đã xoá: 40989

Dataset Construction and Content Concatenation for Vietnamese News Classification

In [ ]:
# Tạo cột content
df_all['content'] = df_all['title'].fillna('') + ' ' + df_all['text'].fillna('')

# Chỉ giữ các cột cần thiết
df = df_all[['content', 'label', 'source']]

# Kiểm tra
print(df.head())
print(df.shape)

                                             content  label     source
0  Trung Quốc kêu gọi người trẻ hiến tinh trùng M...     10  VNExpress
1  Ngôi nhà hoa hồng của vợ chồng Việt ở Đức Năm ...     10  VNExpress
2  Tình thế 'nước đến chân mới nhảy' của Ukraine ...      6  VNExpress
3  Đặng Thanh Ngân đoạt á hậu 4 Hoa hậu Siêu quốc...      2  VNExpress
4  Vợ chồng nên quan hệ bao nhiêu lần mỗi tuần? "...     10  VNExpress
(972214, 3)

In [ ]:
word_count = df['content'].str.count(r'\s+') + 1

print(word_count.describe())

count    972214.000000
mean        597.404829
std         374.538494
min           8.000000
25%         351.000000
50%         514.000000
75%         762.000000
max       40323.000000
Name: content, dtype: float64

Vietnamese Text Preprocessing and Stopword Removal for News Classification

In [ ]:
import re

# load stopwords (file txt mỗi dòng 1 từ)
with open("vietnamese-stopwords.txt", "r", encoding="utf-8") as f:
    stopwords = set(f.read().splitlines())

def clean_text(text):
    # chữ thường
    text = text.lower()

    # bỏ dấu câu
    text = re.sub(r'[^\w\s]', ' ', text)

    # bỏ số (tuỳ chọn)
    text = re.sub(r'\d+', ' ', text)

    # bỏ nhiều khoảng trắng
    text = re.sub(r'\s+', ' ', text).strip()

    # bỏ stopwords
    words = text.split()
    words = [w for w in words if w not in stopwords]

    return " ".join(words)

# áp dụng
df['content'] = df['content'].apply(clean_text)

/tmp/ipykernel_7480/2290600701.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = df['content'].apply(clean_text)

Vietnamese Word Segmentation using Underthesea with Parallel Processing

In [ ]:
# pip install underthesea
from underthesea import word_tokenize
from multiprocessing import Pool, cpu_count
from tqdm import tqdm

def tokenize_text(text):
    if not text or not isinstance(text, str):
        return ""
    try:
        return word_tokenize(text, format="text")
    except Exception as e:
        print(f"Lỗi khi tokenize: {e}")
        return text

if __name__ == "__main__":
    texts = df['content'].tolist()

    workers = max(1, cpu_count() - 1)

    with Pool(workers) as pool:
        results = list(
            tqdm(
                pool.imap(tokenize_text, texts),
                total=len(texts)
            )
        )

    df['content'] = results

100%|██████████| 972214/972214 [1:08:39<00:00, 236.01it/s]
/tmp/ipykernel_7480/1338221990.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content'] = results

In [ ]:
df

                                                  content  label     source
0       trung_quốc kêu_gọi trẻ hiến tinh_trùng zhong m...     10  VNExpress
1       hoa_hồng vợ_chồng việt_đức vợ_chồng phương_quỳ...     10  VNExpress
2       tình chân nhảy_ukraine nga công_chiếm thành_ph...      6  VNExpress
3       đặng_ngân_đoạt hậu hoa_hậu_siêu quốc_gia thí_s...      2  VNExpress
4       vợ_chồng quan_hệ bao_nhiêu tuần_hài đời_sống t...     10  VNExpress
...                                                   ...    ...        ...
972209  tình_yêu chàng trai vợ almeda hardwich maryvil...     10  VNExpress
972210  tp hcm chuẩn giường_trị covid ổ dịch phức_tạp ...      5  VNExpress
972211  mobifone tổ_chức giải đấu esports sinh_viên mo...      1  VNExpress
972212  đại_học ngân_hàng tp hcm tân_hiệu_trưởng ngoái...      1  VNExpress
972213  áp_lực thực_hiện trường_học hạnh_phúc tọa_đàm ...      1  VNExpress

[972214 rows x 3 columns]

In [ ]:
df.columns

Index(['content', 'label', 'source'], dtype='object')

In [ ]:
word_count = df['content'].str.count(r'\s+') + 1

print(word_count.describe())

count    972214.000000
mean        224.779105
std         135.793707
min           2.000000
25%         135.000000
50%         197.000000
75%         286.000000
max       16423.000000
Name: content, dtype: float64

Data filtering

In [ ]:
df = df[df['content'].str.count(r'\s+') + 1 >= 50].reset_index(drop=True)

print(f"Số dòng còn lại: {len(df):,}")

Số dòng còn lại: 946,696

In [ ]:
df.columns

Index(['content', 'label', 'source'], dtype='object')

## Data Splitting

In [ ]:
from sklearn.model_selection import train_test_split

# Bước 1: tách train (80%) và temp (20%)
train_df, temp_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df['label'],   # giữ phân bố label
    random_state=42
)

# Bước 2: tách temp thành val (10%) và test (10%)
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,          # chia đôi 20% → 10% + 10%
    stratify=temp_df['label'],
    random_state=42
)

# Reset index (khuyến nghị)
train_df = train_df.reset_index(drop=True)
val_df   = val_df.reset_index(drop=True)
test_df  = test_df.reset_index(drop=True)

Balanced sampling is applied to reduce class imbalance by limiting each category to an equal number of samples based on the target dataset size. This helps improve model fairness and overall classification performance across different classes.

In [ ]:
target_size = 200000
num_classes = train_df['label'].nunique()

samples_per_class = target_size // num_classes

train_df = train_df.groupby('label', group_keys=False).apply(
    lambda x: x.sample(
        n=min(len(x), samples_per_class),
        random_state=42
    )
).reset_index(drop=True)

/tmp/ipykernel_2114/2924742261.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_df = train_df.groupby('label', group_keys=False).apply(

In [ ]:
train_df.shape, val_df.shape, test_df.shape

((200000, 3), (94670, 3), (94670, 3))

# Training models

 Fine-Tuning Transformer Models with LoRA for Vietnamese News Classification

In [ ]:
# ==================== IMPORT ====================
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback,
    DataCollatorWithPadding
)

from peft import LoraConfig, get_peft_model, TaskType

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    roc_auc_score,
    classification_report
)

import pandas as pd


# ==================== LABEL ENCODER ====================
le = LabelEncoder()
train_labels = le.fit_transform(train_df['label'])
val_labels   = le.transform(val_df['label'])
test_labels  = le.transform(test_df['label'])

num_labels = len(set(train_labels))


# ==================== DATASET ====================
class NewsDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = int(self.labels[idx])

        encoding = self.tokenizer(
            text,
            truncation=True,
            max_length=self.max_len
        )

        encoding["labels"] = label
        return encoding


# ==================== METRICS ====================
def compute_metrics(pred):
    labels = pred.label_ids
    logits = pred.predictions

    preds = logits.argmax(axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average='macro', zero_division=0
    )
    acc = accuracy_score(labels, preds)

    try:
        probs = F.softmax(torch.tensor(logits), dim=1).numpy()
        auc = roc_auc_score(labels, probs, multi_class='ovr')
    except:
        auc = 0.0

    return {
        'accuracy': acc,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'auc': auc
    }


# ==================== TRAINING ARGS ====================
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=2,
    learning_rate=1e-5,
    warmup_steps=300,
    weight_decay=0.01,

    eval_strategy='epoch',
    save_strategy='epoch',
    logging_steps=50,

    load_best_model_at_end=True,
    metric_for_best_model='f1',
    greater_is_better=True,

    save_total_limit=2,
    fp16=torch.cuda.is_available(),

    dataloader_num_workers=2,
    dataloader_pin_memory=True,

    report_to="none"
)


# ==================== MODEL LIST ====================
model_names = {
    # "phobert": "vinai/phobert-base-v2",
    "xlm": "xlm-roberta-base",
    "mbert": "bert-base-multilingual-cased"
}


# ==================== TRAIN FUNCTION ====================
def train_model(model_name, model_path):
    print(f"\n🚀 Training {model_name}...")

    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)

    train_dataset = NewsDataset(train_df['content'].tolist(), train_labels, tokenizer)
    val_dataset   = NewsDataset(val_df['content'].tolist(), val_labels, tokenizer)
    test_dataset  = NewsDataset(test_df['content'].tolist(), test_labels, tokenizer)

    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    model = AutoModelForSequenceClassification.from_pretrained(
        model_path,
        num_labels=num_labels,
        ignore_mismatched_sizes=True
    )

    # LoRA
    lora_config = LoraConfig(
        task_type=TaskType.SEQ_CLS,
        r=8,
        lora_alpha=16,
        lora_dropout=0.1,
        bias="none"
    )

    model = get_peft_model(model, lora_config)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        data_collator=data_collator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=1)]
    )

    # ==================== TRAIN ====================
    trainer.train()

    # ==================== EVAL ====================
    results = trainer.evaluate(test_dataset)

    print(f"\n===== {model_name.upper()} RESULTS =====")
    print(f"Accuracy   : {results['eval_accuracy']*100:.2f}")
    print(f"Precision  : {results['eval_precision']*100:.2f}")
    print(f"Recall     : {results['eval_recall']*100:.2f}")
    print(f"Macro-F1   : {results['eval_f1']*100:.2f}")
    print(f"AUC        : {results['eval_auc']*100:.2f}")

    # ==================== PER-CLASS REPORT ====================
    predictions = trainer.predict(test_dataset)

    y_pred = predictions.predictions.argmax(axis=-1)
    y_true = predictions.label_ids

    print("\n📊 Per-class report:")

    print(classification_report(
        y_true,
        y_pred,
        target_names=[str(x) for x in le.classes_],
        digits=4
    ))

    # DataFrame
    report_dict = classification_report(
        y_true,
        y_pred,
        target_names=[str(x) for x in le.classes_],
        output_dict=True
    )

    df_report = pd.DataFrame(report_dict).transpose()
    df_report = df_report.iloc[:-3]

    df_report['support'] = df_report['support'].astype(int)
    df_report = df_report.sort_values(by="support", ascending=False)

    print("\n📊 Per-class sorted by size:")
    print(df_report[['precision', 'recall', 'f1-score', 'support']])

    # Save CSV
    df_report.to_csv(f"{model_name}_per_class_report.csv")

    return results


# ==================== RUN ALL ====================
all_results = {}

for name, path in model_names.items():
    results = train_model(name, path)
    all_results[name] = results

🚀 Training xlm...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== XLM RESULTS =====
Accuracy   : 82.65
Precision  : 80.80
Recall     : 82.78
Macro-F1   : 81.60
AUC        : 97.94

📊 Per-class report:
              precision    recall  f1-score   support

           1     0.7994    0.8831    0.8392      5980
           2     0.8435    0.8643    0.8538      9079
           3     0.8498    0.7515    0.7976     12600
           4     0.7175    0.8548    0.7802      6880
           5     0.8405    0.8855    0.8624      9943
           6     0.8824    0.8714    0.8769     13791
           7     0.9668    0.9586    0.9627     12439
           8     0.7885    0.6797    0.7301     13748
           9     0.8334    0.9336    0.8807      4731
          10     0.5583    0.5952    0.5761      5479

    accuracy                         0.8265     94670
   macro avg     0.8080    0.8278    0.8160     94670
weighted avg     0.8289    0.8265    0.8259     94670


📊 Per-class sorted by size:
    precision    recall  f1-score  support
6    0.882379  0.871438  0.876874    13791
8    0.788541  0.679735  0.730107    13748
3    0.849771  0.751508  0.797625    12600
7    0.966759  0.958598  0.962661    12439
5    0.840493  0.885548  0.862432     9943
2    0.843491  0.864302  0.853770     9079
4    0.717545  0.854797  0.780180     6880
1    0.799425  0.883110  0.839186     5980
10   0.558295  0.595182  0.576148     5479
9    0.833396  0.933629  0.880670     4731

🚀 Training mbert...

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== MBERT RESULTS =====
Accuracy   : 79.84
Precision  : 78.10
Recall     : 80.30
Macro-F1   : 78.73
AUC        : 97.04

📊 Per-class report:
              precision    recall  f1-score   support

           1     0.7950    0.8781    0.8345      5980
           2     0.8392    0.8108    0.8248      9079
           3     0.8407    0.7184    0.7748     12600
           4     0.6199    0.8810    0.7277      6880
           5     0.8298    0.8682    0.8486      9943
           6     0.8791    0.8362    0.8571     13791
           7     0.9673    0.9474    0.9572     12439
           8     0.7689    0.6197    0.6863     13748
           9     0.7939    0.8930    0.8405      4731
          10     0.4764    0.5773    0.5220      5479

    accuracy                         0.7984     94670
   macro avg     0.7810    0.8030    0.7873     94670
weighted avg     0.8088    0.7984    0.7994     94670


📊 Per-class sorted by size:
    precision    recall  f1-score  support
6    0.879097  0.836198  0.857111    13791
8    0.768884  0.619727  0.686294    13748
3    0.840717  0.718413  0.774768    12600
7    0.967252  0.947423  0.957235    12439
5    0.829777  0.868249  0.848577     9943
2    0.839243  0.810772  0.824762     9079
4    0.619861  0.880959  0.727698     6880
1    0.795004  0.878094  0.834485     5980
10   0.476355  0.577295  0.521990     5479
9    0.793874  0.893046  0.840545     4731

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    roc_auc_score,
    classification_report
)
# ==================== PER-CLASS ====================
print("\n📊 Per-class report:")
#Phobert
print(classification_report(
    y_true,
    y_pred,
    target_names=[str(x) for x in le.classes_],
    digits=4
))

📊 Per-class report:
              precision    recall  f1-score   support

           1     0.8576    0.9162    0.8859      5980
           2     0.9085    0.9355    0.9218      9079
           3     0.9032    0.7993    0.8481     12600
           4     0.7831    0.9067    0.8404      6880
           5     0.8899    0.9117    0.9006      9943
           6     0.9273    0.9029    0.9149     13791
           7     0.9780    0.9818    0.9799     12439
           8     0.8587    0.7633    0.8082     13748
           9     0.8840    0.9647    0.9226      4731
          10     0.6201    0.7164    0.6647      5479

    accuracy                         0.8767     94670
   macro avg     0.8610    0.8798    0.8687     94670
weighted avg     0.8802    0.8767    0.8769     94670

Learning Curve Analysis for TF-IDF Based Machine Learning Models

In [ ]:
# ===================== 1. IMPORT =====================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.base import clone

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV


# ===================== 2. DATA =====================
X = df['content']
y = df['label']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print(f"Train: {len(X_train):,} | Test: {len(X_test):,}")
print(f"Số class: {len(le.classes_)}")


# ===================== 3. TF-IDF (FIT 1 LẦN) =====================
tfidf = TfidfVectorizer(
    max_features=100000,
    ngram_range=(1, 2),
    sublinear_tf=True,
    min_df=5,
    max_df=0.95
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

print(f"Vocab size: {len(tfidf.vocabulary_):,}")


# ===================== 4. MODELS =====================
ml_models = {

    "Naive Bayes":
        MultinomialNB(),

    "Logistic Regression":
        LogisticRegression(
            class_weight='balanced',
            max_iter=1000,
            random_state=42,
            n_jobs=-1
        ),

    "LinearSVC":
        CalibratedClassifierCV(
            LinearSVC(
                class_weight='balanced',
                C=1.0,
                max_iter=2000,
                random_state=42
            ),
            method='sigmoid',
            cv=3
        ),

    "SGDClassifier":
        SGDClassifier(
            loss='log_loss',
            class_weight='balanced',
            random_state=42,
            n_jobs=-1
        ),
}


# ===================== 5. LEARNING CURVE =====================
train_sizes = [0.01, 0.05, 0.1, 0.25, 0.5]
learning_results = []

for name, model in ml_models.items():

    print(f"\n🔥 Model: {name}")
    f1_list = []

    for frac in train_sizes:

        print(f"   ➤ Training với {int(frac*100)}% data")

        # Stratified sampling trực tiếp trên TF-IDF (nhanh hơn)
        idx = np.arange(X_train_tfidf.shape[0])

        idx_sub, _ = train_test_split(
            idx,
            train_size=frac,
            stratify=y_train,
            random_state=42
        )

        X_sub = X_train_tfidf[idx_sub]
        y_sub = y_train[idx_sub]

        # clone model
        model_clone = clone(model)

        # train
        model_clone.fit(X_sub, y_sub)

        # predict
        y_pred = model_clone.predict(X_test_tfidf)

        f1 = f1_score(y_test, y_pred, average="macro")
        f1_list.append(round(f1, 4))

    print("F1-macro:", f1_list)

    learning_results.append({
        "Model": name,
        "Train_Sizes": train_sizes,
        "F1_List": f1_list
    })


# ===================== 6. RESULT =====================
df_learning = pd.DataFrame(learning_results)

print("\n" + "="*60)
print("LEARNING CURVE RESULT")
print("="*60)
print(df_learning.to_string(index=False))


# ===================== 7. SAVE =====================
df_learning.to_csv("learning_curve.csv", index=False)
print("\n✅ Saved learning_curve.csv")


# ===================== 8. PLOT =====================
plt.figure(figsize=(8,5))

for _, row in df_learning.iterrows():
    plt.plot(
        [x*100 for x in row["Train_Sizes"]],
        row["F1_List"],
        marker='o',
        label=row["Model"]
    )

plt.xlabel("Training Data (%)")
plt.ylabel("Macro F1")
plt.title("Learning Curve (TF-IDF Models)")
plt.legend()
plt.grid()
plt.tight_layout()
plt.show()

Train: 757,356 | Test: 189,340
Số class: 10

# Debug

In [ ]:
from datasets import load_dataset
import pandas as pd

# ================================
# 2. WORD COUNT
# ================================
df["word_count"] = df["content"].str.split().str.len()

# ================================
# 3. BASIC STATISTICS
# ================================
stats = df.groupby("label").agg(
    Articles=("content", "count"),
    Avg_words=("word_count", "mean"),
    Min_words=("word_count", "min"),
    Max_words=("word_count", "max")
).reset_index()

stats["Avg_words"] = stats["Avg_words"].round(2)

# ================================
# 4. UNIQUE WORDS
# ================================
def count_unique(texts):
    vocab = set()
    for t in texts:
        vocab.update(t.split())
    return len(vocab)

stats["Unique_words"] = (
    df.groupby("label")["content"]
    .apply(count_unique)
    .values
)

# ================================
# 5. TRAIN / DEV / TEST SPLIT
# ================================
stats["Train"] = (stats["Articles"] * 0.8).astype(int)
stats["Dev"] = (stats["Articles"] * 0.1).astype(int)
stats["Test"] = stats["Articles"] - stats["Train"] - stats["Dev"]

# ================================
# 6. RENAME COLUMNS
# ================================
stats = stats.rename(columns={
    "label": "Category",
    "Articles": "#Articles",
    "Avg_words": "Avg.words",
    "Min_words": "Min words",
    "Max_words": "Max words",
    "Unique_words": "Unique words"
})

# ================================
# 7. PRINT RESULT
# ================================
print("\nDataset Statistics")
print(stats.to_string(index=False))

Dataset Statistics
 Category  #Articles  Avg.words  Min words  Max words  Unique words  Train   Dev  Test
        1      59796     255.45         50       4197        563031  47836  5979  5981
        2      90791     244.03         50       2243       1223072  72632  9079  9080
        3     126006     274.22         50       4335        981351 100804 12600 12602
        4      68792     182.23         50       1407        488742  55033  6879  6880
        5      99430     244.37         50       6634        740240  79544  9943  9943
        6     137909     201.52         50       2778        987715 110327 13790 13792
        7     124393     200.57         50       2232        859468  99514 12439 12440
        8     137475     225.36         50      16423        719229 109980 13747 13748
        9      47310     231.71         50       2142        406442  37848  4731  4731
       10      54794     261.16         50       2245        805730  43835  5479  5480

Statistical Analysis and Data Splitting of the Vietnamese News Dataset

In [ ]:
# ================================
# TỔNG HỢP TOÀN BỘ DATASET
# ================================
total_row = pd.DataFrame([{
    "Category":      "Total",
    "#Articles":     stats["#Articles"].sum(),
    "Avg.words":     round(stats["Avg.words"].mean(), 1),
    "Min words":     stats["Min words"].min(),
    "Max words":     stats["Max words"].max(),
    "Unique words":  stats["Unique words"].sum(),   # hoặc .max() nếu tính unique toàn tập
}])

stats_with_total = pd.concat([stats, total_row], ignore_index=True)

# ================================
# TRAIN / DEV / TEST SIZE
# ================================
n_total = stats["#Articles"].sum()
n_test  = int(n_total * 0.2)
n_temp  = n_total - n_test
n_val   = int(n_temp * 0.125)   # 10% tổng
n_train = n_temp - n_val

split_row = pd.DataFrame([{
    "Category":      "Split",
    "#Articles":     f"Train {n_train:,} / Val {n_val:,} / Test {n_test:,}",
    "Avg.words":     "",
    "Min words":     "",
    "Max words":     "",
    "Unique words":  "",
}])

stats_final = pd.concat([stats_with_total, split_row], ignore_index=True)

print("\nDataset Statistics")
print(stats_final.to_string(index=False))

Dataset Statistics
Category                                 #Articles Avg.words Min words Max words Unique words    Train     Dev    Test
       1                                     59796    255.45        50      4197       563031  47836.0  5979.0  5981.0
       2                                     90791    244.03        50      2243      1223072  72632.0  9079.0  9080.0
       3                                    126006    274.22        50      4335       981351 100804.0 12600.0 12602.0
       4                                     68792    182.23        50      1407       488742  55033.0  6879.0  6880.0
       5                                     99430    244.37        50      6634       740240  79544.0  9943.0  9943.0
       6                                    137909    201.52        50      2778       987715 110327.0 13790.0 13792.0
       7                                    124393    200.57        50      2232       859468  99514.0 12439.0 12440.0
       8                                    137475    225.36        50     16423       719229 109980.0 13747.0 13748.0
       9                                     47310    231.71        50      2142       406442  37848.0  4731.0  4731.0
      10                                     54794    261.16        50      2245       805730  43835.0  5479.0  5480.0
   Total                                    946696     232.1        50     16423      7775020      NaN     NaN     NaN
   Split Train 662,688 / Val 94,669 / Test 189,339                                                 NaN     NaN     NaN

Stratified Train-Test Splitting for Vietnamese News Classification Dataset

In [ ]:
from sklearn.model_selection import train_test_split

X = df['content']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y   # ✅ giữ tỷ lệ label cân bằng giữa train/test
)

print(f"Train: {len(X_train):,} | Test: {len(X_test):,}")
print("\nPhân phối label train:")
print(y_train.value_counts(normalize=True).round(3))
print("\nPhân phối label test:")
print(y_test.value_counts(normalize=True).round(3))

Train: 757,356 | Test: 189,340

Phân phối label train:
label
6     0.146
8     0.145
3     0.133
7     0.131
5     0.105
2     0.096
4     0.073
1     0.063
10    0.058
9     0.050
Name: proportion, dtype: float64

Phân phối label test:
label
6     0.146
8     0.145
3     0.133
7     0.131
5     0.105
2     0.096
4     0.073
1     0.063
10    0.058
9     0.050
Name: proportion, dtype: float64

# Performance Comparison of Traditional Machine Learning Models using TF-IDF Features for Vietnamese News Classification

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

# ============================================================
# 1. CHUẨN BỊ DỮ LIỆU
# ============================================================
X = df['content']
y = df['label']

# encode label nếu là string
le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print(f"Train: {len(X_train):,} | Test: {len(X_test):,}")
print(f"Số class: {len(le.classes_)} → {list(le.classes_)}")

# ============================================================
# 2. TF-IDF
# ============================================================
tfidf = TfidfVectorizer(
    max_features=100_000,
    ngram_range=(1, 2),
    sublinear_tf=True,
    min_df=5,
    max_df=0.95,
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)   # ✅ chỉ transform

print(f"Vocab size: {len(tfidf.vocabulary_):,}")

# ============================================================
# 3. ĐỊNH NGHĨA CÁC MÔ HÌNH
# ============================================================
models = {
    "Naive Bayes":         MultinomialNB(),
    "Logistic Regression": LogisticRegression(
                               class_weight='balanced',
                               max_iter=1000,
                               random_state=42
                           ),
    "LinearSVC":           LinearSVC(
                               class_weight='balanced',
                               C=1.0,
                               max_iter=2000,
                               random_state=42
                           ),
    "Random Forest":       RandomForestClassifier(
                               class_weight='balanced',
                               n_estimators=300,
                               random_state=42,
                               n_jobs=-1
                           ),
    "XGBoost":             XGBClassifier(
                               n_estimators=300,
                               learning_rate=0.1,
                               use_label_encoder=False,
                               eval_metric='mlogloss',
                               random_state=42,
                               n_jobs=-1
                           ),
}

# ============================================================
# 4. TRAIN & ĐÁNH GIÁ
# ============================================================
results = []

for name, model in models.items():
    print(f"\n⏳ Đang train: {name}...")
    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)

    report = classification_report(y_test, y_pred, output_dict=True)

    results.append({
        "Model":     name,
        "Precision": round(report['macro avg']['precision'], 4),
        "Recall":    round(report['macro avg']['recall'],    4),
        "F1-Macro":  round(report['macro avg']['f1-score'],  4),
        "Accuracy":  round(accuracy_score(y_test, y_pred),   4),
    })

    # in chi tiết từng class
    print(classification_report(
          y_test, y_pred,
          target_names=[str(c) for c in le.classes_]
    ))

# ============================================================
# 5. BẢNG KẾT QUẢ TỔNG HỢP
# ============================================================
df_results = (
    pd.DataFrame(results)
    .sort_values("F1-Macro", ascending=False)
    .reset_index(drop=True)
)

print("\n" + "="*60)
print("BẢNG KẾT QUẢ TỔNG HỢP")
print("="*60)
print(df_results.to_string(index=False))

# ============================================================
# 6. LƯU KẾT QUẢ
# ============================================================
df_results.to_csv("results.csv", index=False)
print("\n✅ Đã lưu kết quả vào results.csv")

Train: 757,356 | Test: 189,340
Số class: 10 → [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]
Vocab size: 100,000

⏳ Đang train: Naive Bayes...
              precision    recall  f1-score   support

           1       0.90      0.85      0.87     11959
           2       0.89      0.93      0.90     18158
           3       0.89      0.81      0.85     25201
           4       0.74      0.90      0.82     13759
           5       0.90      0.91      0.90     19886
           6       0.94      0.90      0.92     27582
           7       0.99      0.97      0.98     24879
           8       0.83      0.76      0.80     27495
           9       0.93      0.95      0.94      9462
          10       0.60      0.73      0.66     10959

    accuracy                           0.87    189340
   macro avg       0.86      0.87      0.86    189340
weighted avg       0.88      0.87      0.87    189340


⏳ Đang train: Logistic Regression...
              precision    recall  f1-score   support

           1       0.91      0.93      0.92     11959
           2       0.96      0.95      0.95     18158
           3       0.92      0.88      0.90     25201
           4       0.83      0.93      0.88     13759
           5       0.93      0.95      0.94     19886
           6       0.97      0.95      0.96     27582
           7       0.99      0.99      0.99     24879
           8       0.90      0.83      0.86     27495
           9       0.94      0.98      0.96      9462
          10       0.74      0.82      0.78     10959

    accuracy                           0.92    189340
   macro avg       0.91      0.92      0.91    189340
weighted avg       0.92      0.92      0.92    189340


⏳ Đang train: LinearSVC...
              precision    recall  f1-score   support

           1       0.92      0.93      0.93     11959
           2       0.96      0.96      0.96     18158
           3       0.92      0.90      0.91     25201
           4       0.86      0.91      0.89     13759
           5       0.94      0.95      0.95     19886
           6       0.97      0.97      0.97     27582
           7       0.99      0.99      0.99     24879
           8       0.90      0.86      0.88     27495
           9       0.96      0.97      0.97      9462
          10       0.79      0.80      0.79     10959

    accuracy                           0.93    189340
   macro avg       0.92      0.93      0.92    189340
weighted avg       0.93      0.93      0.93    189340


⏳ Đang train: Random Forest...
              precision    recall  f1-score   support

           1       0.90      0.89      0.89     11959
           2       0.90      0.93      0.92     18158
           3       0.86      0.87      0.86     25201
           4       0.82      0.89      0.85     13759
           5       0.89      0.93      0.91     19886
           6       0.93      0.93      0.93     27582
           7       0.98      0.99      0.98     24879
           8       0.84      0.81      0.83     27495
           9       0.95      0.95      0.95      9462
          10       0.79      0.57      0.66     10959

    accuracy                           0.89    189340
   macro avg       0.88      0.88      0.88    189340
weighted avg       0.89      0.89      0.89    189340


⏳ Đang train: XGBoost...

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [14:37:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score
# ============================================================
# 1. CHUẨN BỊ DỮ LIỆU
# ============================================================
X = df['content']
y = df['label']

le        = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print(f"Train: {len(X_train):,} | Test: {len(X_test):,}")
print(f"Số class: {len(le.classes_)} → {list(le.classes_)}")

# ============================================================
# 2. TF-IDF
# ============================================================
tfidf_full = TfidfVectorizer(ngram_range=(1,2), sublinear_tf=True, min_df=5)
tfidf_full.fit(X_train)
auto_max_features = min(int(len(tfidf_full.vocabulary_) * 0.6), 100_000)
print(f"→ auto_max_features: {auto_max_features:,}")
del tfidf_full  # ✅ giải phóng RAM sau khi đã tính xong

tfidf = TfidfVectorizer(
    max_features=auto_max_features,
    ngram_range=(1, 2),
    sublinear_tf=True,
    min_df=5,
    max_df=0.95,
)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)
print(f"Vocab size: {len(tfidf.vocabulary_):,}")

# ============================================================
# 3. ĐỊNH NGHĨA CÁC MÔ HÌNH
# ============================================================
ml_models = {
    "Naive Bayes":         MultinomialNB(),
    "Logistic Regression": LogisticRegression(
                               class_weight='balanced',
                               max_iter=1000,
                               random_state=42
                           ),
    "LinearSVC":           LinearSVC(
                               class_weight='balanced',
                               C=1.0,
                               max_iter=2000,
                               random_state=42
                           ),
    "SGDClassifier":       SGDClassifier(
                               loss='hinge',
                               class_weight='balanced',
                               random_state=42,
                               n_jobs=-1
                           ),
}

# ============================================================
# 4. TRAIN & ĐÁNH GIÁ
# ============================================================

target_names = [str(c) for c in le.classes_]
results = []

for name, model in ml_models.items():

    print(f"\n⏳ Đang train: {name}...")

    model.fit(X_train_tfidf, y_train)

    y_pred = model.predict(X_test_tfidf)

    # ================= AUC =================
    try:
        if hasattr(model, "predict_proba"):
            y_score = model.predict_proba(X_test_tfidf)
        else:
            y_score = model.decision_function(X_test_tfidf)

        auc = roc_auc_score(
            y_test,
            y_score,
            multi_class="ovr",
            average="macro"
        )

    except Exception:
        auc = np.nan
    # ======================================

    report = classification_report(
        y_test,
        y_pred,
        output_dict=True,
        target_names=target_names
    )

    results.append({
        "Model": name,
        "Precision": round(report['macro avg']['precision'], 4),
        "Recall": round(report['macro avg']['recall'], 4),
        "F1-Macro": round(report['macro avg']['f1-score'], 4),
        "Accuracy": round(accuracy_score(y_test, y_pred), 4),
        "AUC": round(auc, 4) if not np.isnan(auc) else None
    })

    print(classification_report(y_test, y_pred, target_names=target_names))
# ============================================================
# 5. BẢNG KẾT QUẢ TỔNG HỢP
# ============================================================
df_results = (
    pd.DataFrame(results)
    .sort_values("F1-Macro", ascending=False)
    .reset_index(drop=True)
)
print("\n" + "="*60)
print("BẢNG KẾT QUẢ TỔNG HỢP")
print("="*60)
print(df_results.to_string(index=False))

# ============================================================
# 6. LƯU KẾT QUẢ
# ============================================================
df_results.to_csv("results1.csv", index=False)
print("\n✅ Đã lưu kết quả vào results1.csv")

Train: 757,356 | Test: 189,340
Số class: 10 → [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]
→ auto_max_features: 100,000
Vocab size: 100,000

⏳ Đang train: Naive Bayes...
              precision    recall  f1-score   support

           1       0.90      0.85      0.87     11959
           2       0.89      0.93      0.90     18158
           3       0.89      0.81      0.85     25201
           4       0.74      0.90      0.82     13759
           5       0.90      0.91      0.90     19886
           6       0.94      0.90      0.92     27582
           7       0.99      0.97      0.98     24879
           8       0.83      0.76      0.80     27495
           9       0.93      0.95      0.94      9462
          10       0.60      0.73      0.66     10959

    accuracy                           0.87    189340
   macro avg       0.86      0.87      0.86    189340
weighted avg       0.88      0.87      0.87    189340


⏳ Đang train: Logistic Regression...
              precision    recall  f1-score   support

           1       0.91      0.93      0.92     11959
           2       0.96      0.95      0.95     18158
           3       0.92      0.88      0.90     25201
           4       0.83      0.93      0.88     13759
           5       0.93      0.95      0.94     19886
           6       0.97      0.95      0.96     27582
           7       0.99      0.99      0.99     24879
           8       0.90      0.83      0.86     27495
           9       0.94      0.98      0.96      9462
          10       0.74      0.82      0.78     10959

    accuracy                           0.92    189340
   macro avg       0.91      0.92      0.91    189340
weighted avg       0.92      0.92      0.92    189340


⏳ Đang train: LinearSVC...
              precision    recall  f1-score   support

           1       0.92      0.93      0.93     11959
           2       0.96      0.96      0.96     18158
           3       0.92      0.90      0.91     25201
           4       0.86      0.91      0.89     13759
           5       0.94      0.95      0.95     19886
           6       0.97      0.97      0.97     27582
           7       0.99      0.99      0.99     24879
           8       0.90      0.86      0.88     27495
           9       0.96      0.97      0.97      9462
          10       0.79      0.80      0.79     10959

    accuracy                           0.93    189340
   macro avg       0.92      0.93      0.92    189340
weighted avg       0.93      0.93      0.93    189340


⏳ Đang train: SGDClassifier...
              precision    recall  f1-score   support

           1       0.88      0.92      0.90     11959
           2       0.93      0.94      0.93     18158
           3       0.89      0.85      0.87     25201
           4       0.79      0.91      0.84     13759
           5       0.89      0.94      0.91     19886
           6       0.95      0.92      0.93     27582
           7       0.98      0.99      0.98     24879
           8       0.87      0.78      0.82     27495
           9       0.90      0.97      0.94      9462
          10       0.72      0.71      0.72     10959

    accuracy                           0.89    189340
   macro avg       0.88      0.89      0.88    189340
weighted avg       0.89      0.89      0.89    189340


============================================================
BẢNG KẾT QUẢ TỔNG HỢP
============================================================
              Model  Precision  Recall  F1-Macro  Accuracy    AUC
          LinearSVC     0.9201  0.9256    0.9227    0.9286    NaN
Logistic Regression     0.9083  0.9204    0.9136    0.9192 0.9955
      SGDClassifier     0.8794  0.8925    0.8849    0.8926    NaN
        Naive Bayes     0.8603  0.8709    0.8636    0.8706 0.9883

✅ Đã lưu kết quả vào results1.csv

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.calibration import CalibratedClassifierCV

# ============================================================
# 1. CHUẨN BỊ DỮ LIỆU
# ============================================================
X = df['content']
y = df['label']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print(f"Train: {len(X_train):,} | Test: {len(X_test):,}")
print(f"Số class: {len(le.classes_)} → {list(le.classes_)}")

# ============================================================
# 2. TF-IDF
# ============================================================
tfidf_full = TfidfVectorizer(ngram_range=(1,2), sublinear_tf=True, min_df=5)
tfidf_full.fit(X_train)

auto_max_features = min(int(len(tfidf_full.vocabulary_) * 0.6), 100_000)
print(f"→ auto_max_features: {auto_max_features:,}")

del tfidf_full

tfidf = TfidfVectorizer(
    max_features=auto_max_features,
    ngram_range=(1,2),
    sublinear_tf=True,
    min_df=5,
    max_df=0.95
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

print(f"Vocab size: {len(tfidf.vocabulary_):,}")

# ============================================================
# 3. MÔ HÌNH
# ============================================================

# ml_models = {

#     "Naive Bayes":
#         MultinomialNB(),

#     "Logistic Regression":
#         LogisticRegression(
#             class_weight='balanced',
#             max_iter=1000,
#             random_state=42
#         ),

#     # LinearSVC được calibrate để có predict_proba
#     "LinearSVC":
#         CalibratedClassifierCV(
#             LinearSVC(
#                 class_weight='balanced',
#                 C=1.0,
#                 max_iter=2000,
#                 random_state=42
#             ),
#             method='sigmoid',
#             cv=3
#         ),

#     # đổi hinge → log_loss để có probability
#     "SGDClassifier":
#         SGDClassifier(
#             loss='log_loss',
#             class_weight='balanced',
#             random_state=42,
#             n_jobs=-1
#         ),
# }

ml_models = {


    # LinearSVC được calibrate để có predict_proba
    "LinearSVC":
        CalibratedClassifierCV(
            LinearSVC(
                class_weight='balanced',
                C=1.0,
                max_iter=2000,
                random_state=42
            ),
            method='sigmoid',
            cv=3
        ),

    # đổi hinge → log_loss để có probability
    "SGDClassifier":
        SGDClassifier(
            loss='log_loss',
            class_weight='balanced',
            random_state=42,
            n_jobs=-1
        ),
}
# ============================================================
# 4. TRAIN & EVALUATE
# ============================================================

target_names = [str(c) for c in le.classes_]
results = []

for name, model in ml_models.items():

    print(f"\n⏳ Training: {name}")

    model.fit(X_train_tfidf, y_train)

    y_pred = model.predict(X_test_tfidf)

    # ===== AUC =====
    try:

        if hasattr(model, "predict_proba"):
            y_score = model.predict_proba(X_test_tfidf)

        else:
            y_score = model.decision_function(X_test_tfidf)

        auc = roc_auc_score(
            y_test,
            y_score,
            multi_class="ovr",
            average="macro"
        )

    except:
        auc = np.nan

    report = classification_report(
        y_test,
        y_pred,
        output_dict=True,
        target_names=target_names
    )

    results.append({
        "Model": name,
        "Precision": round(report['macro avg']['precision'],4),
        "Recall": round(report['macro avg']['recall'],4),
        "F1-Macro": round(report['macro avg']['f1-score'],4),
        "Accuracy": round(accuracy_score(y_test,y_pred),4),
        "AUC": round(auc,4)
    })

    print(classification_report(y_test,y_pred,target_names=target_names))

# ============================================================
# 5. BẢNG KẾT QUẢ
# ============================================================

df_results = (
    pd.DataFrame(results)
    .sort_values("F1-Macro",ascending=False)
    .reset_index(drop=True)
)

print("\n"+"="*60)
print("RESULT TABLE")
print("="*60)
print(df_results.to_string(index=False))

# ============================================================
# 6. SAVE
# ============================================================

df_results.to_csv("results1.csv",index=False)

print("\n✅ Saved results1.csv")

Train: 757,356 | Test: 189,340
Số class: 10 → [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]
→ auto_max_features: 100,000
Vocab size: 100,000

⏳ Training: LinearSVC
              precision    recall  f1-score   support

           1       0.93      0.93      0.93     11959
           2       0.96      0.96      0.96     18158
           3       0.91      0.91      0.91     25201
           4       0.87      0.90      0.89     13759
           5       0.94      0.95      0.95     19886
           6       0.97      0.97      0.97     27582
           7       0.99      0.99      0.99     24879
           8       0.88      0.87      0.88     27495
           9       0.96      0.97      0.97      9462
          10       0.82      0.78      0.80     10959

    accuracy                           0.93    189340
   macro avg       0.92      0.92      0.92    189340
weighted avg       0.93      0.93      0.93    189340


⏳ Training: SGDClassifier
              precision    recall  f1-score   support

           1       0.89      0.89      0.89     11959
           2       0.92      0.91      0.91     18158
           3       0.87      0.84      0.85     25201
           4       0.78      0.88      0.83     13759
           5       0.89      0.92      0.90     19886
           6       0.94      0.90      0.92     27582
           7       0.98      0.98      0.98     24879
           8       0.84      0.77      0.80     27495
           9       0.91      0.96      0.93      9462
          10       0.65      0.72      0.68     10959

    accuracy                           0.88    189340
   macro avg       0.87      0.88      0.87    189340
weighted avg       0.88      0.88      0.88    189340


============================================================
RESULT TABLE
============================================================
        Model  Precision  Recall  F1-Macro  Accuracy    AUC
    LinearSVC     0.9238  0.9231    0.9233    0.9292 0.9955
SGDClassifier     0.8655  0.8768    0.8703    0.8773 0.9895

✅ Saved results1.csv

# Deep Learning Architectures for Vietnamese News Classification

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from torch.utils.data import Dataset, DataLoader
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from sklearn.metrics import roc_auc_score

X = df['content']
y = df['label']

# encode label nếu là string
le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")

num_classes = len(le.classes_)
target_names = [str(c) for c in le.classes_]  # ✅ fix: khai báo 1 lần dùng xuyên suốt

# ============================================================
# 0. KIỂM TRA TRƯỚC KHI CHỌN THAM SỐ
# ============================================================
keras_tok_full = Tokenizer()
keras_tok_full.fit_on_texts(X_train)

total_vocab = len(keras_tok_full.word_index)
lengths     = X_train.str.split().str.len()

print(f"Tổng vocab: {total_vocab:,}")
print(f"\nĐộ dài văn bản:")
print(lengths.describe().round(0))
print(f"\nPercentile:")
print(f"  75%: {lengths.quantile(0.75):.0f} tokens")
print(f"  90%: {lengths.quantile(0.90):.0f} tokens")
print(f"  95%: {lengths.quantile(0.95):.0f} tokens")
print(f"  99%: {lengths.quantile(0.99):.0f} tokens")

MAX_WORDS = min(int(total_vocab * 0.6), 100_000)
MAX_LEN   = int(lengths.quantile(0.95))

print(f"\n→ MAX_WORDS tự động: {MAX_WORDS:,}")
print(f"→ MAX_LEN   tự động: {MAX_LEN}")

# ============================================================
# 1. TOKENIZE
# ============================================================
keras_tok = Tokenizer(num_words=MAX_WORDS, oov_token="<OOV>")
keras_tok.fit_on_texts(X_train)

X_train_seq = pad_sequences(
    keras_tok.texts_to_sequences(X_train),
    maxlen=MAX_LEN, padding='post', truncating='post'
)
X_test_seq = pad_sequences(
    keras_tok.texts_to_sequences(X_test),
    maxlen=MAX_LEN, padding='post', truncating='post'
)

print(f"\nVocab dùng: {len(keras_tok.word_index):,} | X_train: {X_train_seq.shape} | X_test: {X_test_seq.shape}")

# ============================================================
# 2. DATASET
# ============================================================
class TextDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.long)
        self.y = torch.tensor(y, dtype=torch.long)
    def __len__(self):
        return len(self.y)
    def __getitem__(self, i):
        return self.X[i], self.y[i]

train_loader = DataLoader(
    TextDataset(X_train_seq, y_train),
    batch_size=64, shuffle=True, num_workers=2, pin_memory=True
)
test_loader = DataLoader(
    TextDataset(X_test_seq, y_test),
    batch_size=64, shuffle=False, num_workers=2, pin_memory=True
)

# ============================================================
# 3. KIẾN TRÚC
# ============================================================
class TextCNN(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_classes, num_filters=128, kernel_sizes=[2,3,4]):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.convs     = nn.ModuleList([nn.Conv1d(embed_dim, num_filters, k) for k in kernel_sizes])
        self.dropout   = nn.Dropout(0.5)
        self.fc        = nn.Linear(num_filters * len(kernel_sizes), num_classes)

    def forward(self, x):
        x = self.embedding(x).permute(0, 2, 1)
        x = [F.relu(conv(x)).max(dim=2).values for conv in self.convs]
        return self.fc(self.dropout(torch.cat(x, dim=1)))


class BiLSTM(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, num_classes, num_layers=2):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.lstm      = nn.LSTM(embed_dim, hidden_dim, num_layers=num_layers,
                                 batch_first=True, bidirectional=True, dropout=0.3)
        self.dropout   = nn.Dropout(0.5)
        self.fc        = nn.Linear(hidden_dim * 2, num_classes)

    def forward(self, x):
        x = self.embedding(x)
        _, (h, _) = self.lstm(x)
        # ✅ fix: lấy hidden state layer cuối của 2 chiều rồi concat
        out = torch.cat([h[-2], h[-1]], dim=1)
        return self.fc(self.dropout(out))


class TextCNN_BiLSTM(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, num_classes, num_filters=128, kernel_sizes=[2,3,4]):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.convs     = nn.ModuleList([nn.Conv1d(embed_dim, num_filters, k) for k in kernel_sizes])
        self.lstm      = nn.LSTM(embed_dim, hidden_dim, batch_first=True,
                                 bidirectional=True, dropout=0.3)
        self.dropout   = nn.Dropout(0.5)
        self.fc        = nn.Linear(num_filters * len(kernel_sizes) + hidden_dim * 2, num_classes)

    def forward(self, x):
        emb = self.embedding(x)

        # CNN branch
        cnn_out = [F.relu(conv(emb.permute(0,2,1))).max(dim=2).values for conv in self.convs]
        cnn_out = torch.cat(cnn_out, dim=1)

        # LSTM branch
        _, (h, _) = self.lstm(emb)
        lstm_out  = torch.cat([h[-2], h[-1]], dim=1)  # ✅ giống BiLSTM

        return self.fc(self.dropout(torch.cat([cnn_out, lstm_out], dim=1)))

def train_eval(model, train_loader, test_loader, epochs=10, lr=1e-3, patience=3):

    model = model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.5)

    best_f1 = 0
    best_preds = None
    best_probs = None

    patience_counter = 0   # 🔴 đếm số epoch không cải thiện

    for epoch in range(epochs):

        # ===== TRAIN =====
        model.train()
        total_loss = 0

        for X_batch, y_batch in tqdm(train_loader, desc=f"Epoch {epoch+1} Training"):

            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            optimizer.zero_grad()

            logits = model(X_batch)
            loss = criterion(logits, y_batch)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        scheduler.step()

        # ===== EVAL =====
        model.eval()

        all_preds = []
        all_probs = []

        with torch.no_grad():

            for X_batch, _ in tqdm(test_loader, desc=f"Epoch {epoch+1} Evaluating"):

                logits = model(X_batch.to(device))

                probs = torch.softmax(logits, dim=1).cpu().numpy()
                preds = probs.argmax(axis=1)

                all_preds.extend(preds)
                all_probs.extend(probs)

        all_preds = np.array(all_preds)
        all_probs = np.array(all_probs)

        report = classification_report(
            y_test,
            all_preds,
            output_dict=True,
            target_names=target_names
        )

        f1 = report['macro avg']['f1-score']

        print(
            f"Epoch {epoch+1}/{epochs} | "
            f"Loss: {total_loss/len(train_loader):.4f} | "
            f"F1: {f1:.4f}"
        )

        # ===== CHECK IMPROVEMENT =====
        if f1 > best_f1:

            best_f1 = f1
            best_preds = all_preds.copy()
            best_probs = all_probs.copy()

            patience_counter = 0   # reset

        else:
            patience_counter += 1
            print(f"⚠️ No improvement ({patience_counter}/{patience})")

        # ===== EARLY STOP =====
        if patience_counter >= patience:
            print("🛑 Early stopping triggered")
            break

    return best_preds, best_probs, best_f1
# ============================================================
# 5. CHẠY CÁC MODEL
# ============================================================
VOCAB_SIZE = MAX_WORDS + 1
EMBED_DIM  = 128
HIDDEN_DIM = 256

dl_models = {
    "TextCNN":        TextCNN(VOCAB_SIZE, EMBED_DIM, num_classes),
    "BiLSTM":         BiLSTM(VOCAB_SIZE, EMBED_DIM, HIDDEN_DIM, num_classes),
    "TextCNN+BiLSTM": TextCNN_BiLSTM(VOCAB_SIZE, EMBED_DIM, HIDDEN_DIM, num_classes),
}

Device: cuda
Tổng vocab: 794,657

Độ dài văn bản:
count    757356.0
mean        230.0
std         133.0
min          50.0
25%         140.0
50%         200.0
75%         289.0
max       15218.0
Name: content, dtype: float64

Percentile:
  75%: 289 tokens
  90%: 394 tokens
  95%: 465 tokens
  99%: 646 tokens

→ MAX_WORDS tự động: 100,000
→ MAX_LEN   tự động: 465

Vocab dùng: 794,658 | X_train: (757356, 465) | X_test: (189340, 465)

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/rnn.py:990: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.3 and num_layers=1
  super().__init__("LSTM", *args, **kwargs)

==================================================
⏳ Training TextCNN...

Epoch 1 Training: 100%|██████████| 11834/11834 [03:12<00:00, 61.39it/s]
Epoch 1 Evaluating: 100%|██████████| 2959/2959 [00:13<00:00, 227.41it/s]

Epoch 1/10 | Loss: 0.4990 | F1: 0.8900

Epoch 2 Training: 100%|██████████| 11834/11834 [03:10<00:00, 62.05it/s]
Epoch 2 Evaluating: 100%|██████████| 2959/2959 [00:12<00:00, 228.07it/s]

Epoch 2/10 | Loss: 0.3596 | F1: 0.8981

Epoch 3 Training: 100%|██████████| 11834/11834 [03:10<00:00, 62.09it/s]
Epoch 3 Evaluating: 100%|██████████| 2959/2959 [00:12<00:00, 227.71it/s]

Epoch 3/10 | Loss: 0.3245 | F1: 0.9039

Epoch 4 Training: 100%|██████████| 11834/11834 [03:10<00:00, 62.08it/s]
Epoch 4 Evaluating: 100%|██████████| 2959/2959 [00:13<00:00, 227.24it/s]

Epoch 4/10 | Loss: 0.2700 | F1: 0.9097

Epoch 5 Training: 100%|██████████| 11834/11834 [03:10<00:00, 62.01it/s]
Epoch 5 Evaluating: 100%|██████████| 2959/2959 [00:13<00:00, 227.60it/s]

Epoch 5/10 | Loss: 0.2494 | F1: 0.9104

Epoch 6 Training: 100%|██████████| 11834/11834 [03:10<00:00, 62.08it/s]
Epoch 6 Evaluating: 100%|██████████| 2959/2959 [00:13<00:00, 226.90it/s]

Epoch 6/10 | Loss: 0.2367 | F1: 0.9098
⚠️ No improvement (1/3)

Epoch 7 Training: 100%|██████████| 11834/11834 [03:10<00:00, 62.07it/s]
Epoch 7 Evaluating: 100%|██████████| 2959/2959 [00:13<00:00, 227.48it/s]

Epoch 7/10 | Loss: 0.2105 | F1: 0.9131

Epoch 8 Training: 100%|██████████| 11834/11834 [03:10<00:00, 61.97it/s]
Epoch 8 Evaluating: 100%|██████████| 2959/2959 [00:13<00:00, 226.64it/s]

Epoch 8/10 | Loss: 0.2004 | F1: 0.9137

Epoch 9 Training: 100%|██████████| 11834/11834 [03:11<00:00, 61.95it/s]
Epoch 9 Evaluating: 100%|██████████| 2959/2959 [00:13<00:00, 227.38it/s]

Epoch 9/10 | Loss: 0.1930 | F1: 0.9132
⚠️ No improvement (1/3)

Epoch 10 Training: 100%|██████████| 11834/11834 [03:10<00:00, 62.01it/s]
Epoch 10 Evaluating: 100%|██████████| 2959/2959 [00:12<00:00, 227.95it/s]

Epoch 10/10 | Loss: 0.1797 | F1: 0.9144

NameError: name 'roc_auc_score' is not defined

In [ ]:
# ============================================================
# BiGRU — thay BiLSTM
# ============================================================
class BiGRU(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, num_classes, num_layers=2):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.gru       = nn.GRU(embed_dim, hidden_dim, num_layers=num_layers,
                                batch_first=True, bidirectional=True, dropout=0.3)
        self.dropout   = nn.Dropout(0.5)
        self.fc        = nn.Linear(hidden_dim * 2, num_classes)

    def forward(self, x):
        x = self.embedding(x)
        _, h = self.gru(x)
        # Lấy hidden state layer cuối của 2 chiều
        out = torch.cat([h[-2], h[-1]], dim=1)
        return self.fc(self.dropout(out))


# ============================================================
# TextRCNN — BiGRU + Max Pooling
# ============================================================
class TextRCNN(nn.Module):
    def __init__(self, vocab_size, embed_dim, hidden_dim, num_classes):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.gru       = nn.GRU(embed_dim, hidden_dim, batch_first=True,
                                bidirectional=True, dropout=0.3)
        self.dropout   = nn.Dropout(0.5)
        # embed + 2 chiều GRU concat lại
        self.fc        = nn.Linear(embed_dim + hidden_dim * 2, num_classes)

    def forward(self, x):
        emb = self.embedding(x)                        # (B, L, embed_dim)
        gru_out, _ = self.gru(emb)                     # (B, L, hidden_dim*2)

        # Concat embedding + GRU output tại mỗi bước
        combined = torch.cat([emb, gru_out], dim=2)    # (B, L, embed_dim + hidden_dim*2)
        combined = torch.tanh(combined)

        # Max pooling qua toàn sequence
        out = combined.max(dim=1).values               # (B, embed_dim + hidden_dim*2)
        return self.fc(self.dropout(out))


# ============================================================
# Chạy
# ============================================================
VOCAB_SIZE = MAX_WORDS + 1
EMBED_DIM  = 64
HIDDEN_DIM = 128

dl_models = {
    "BiGRU":    BiGRU(VOCAB_SIZE, EMBED_DIM, HIDDEN_DIM, num_classes),
    "TextRCNN": TextRCNN(VOCAB_SIZE, EMBED_DIM, HIDDEN_DIM, num_classes),
    "TextCNN":  TextCNN(VOCAB_SIZE, EMBED_DIM, num_classes),
}

In [ ]:
from sklearn.metrics import roc_auc_score

dl_results = []

for name, model in dl_models.items():

    print(f"\n{'='*50}")
    print(f"⏳ Training {name}...")

    best_preds, best_probs, best_f1 = train_eval(
          model,
          train_loader,
          test_loader,
          epochs=10,
          patience=3
      )

    report = classification_report(
        y_test,
        best_preds,
        output_dict=True,
        target_names=target_names
    )

    auc = roc_auc_score(
        y_test,
        best_probs,
        multi_class="ovr",
        average="macro"
    )

    dl_results.append({
        "Model": name,
        "Nhóm": "Deep Learning",
        "Precision": round(report['macro avg']['precision'], 4),
        "Recall": round(report['macro avg']['recall'], 4),
        "F1-Macro": round(report['macro avg']['f1-score'], 4),
        "Accuracy": round(accuracy_score(y_test, best_preds), 4),
        "AUC": round(auc, 4)
    })

    print(f"✅ {name} → Best F1-Macro: {best_f1:.4f}")
    print(classification_report(y_test, best_preds, target_names=target_names))
df_dl_results = pd.DataFrame(dl_results).sort_values("F1-Macro", ascending=False)

print("\nKết quả Deep Learning:")
print(df_dl_results.to_string(index=False))

==================================================
⏳ Training BiGRU...

Epoch 1 Training: 100%|██████████| 11834/11834 [08:00<00:00, 24.64it/s]
Epoch 1 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.64it/s]

Epoch 1/10 | Loss: 0.3761 | F1: 0.9070

Epoch 2 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 2 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.74it/s]

Epoch 2/10 | Loss: 0.2427 | F1: 0.9161

Epoch 3 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 3 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.54it/s]

Epoch 3/10 | Loss: 0.2113 | F1: 0.9146
⚠️ No improvement (1/3)

Epoch 4 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 4 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.47it/s]

Epoch 4/10 | Loss: 0.1733 | F1: 0.9239

Epoch 5 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 5 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.53it/s]

Epoch 5/10 | Loss: 0.1546 | F1: 0.9235
⚠️ No improvement (1/3)

Epoch 6 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 6 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.19it/s]

Epoch 6/10 | Loss: 0.1413 | F1: 0.9233
⚠️ No improvement (2/3)

Epoch 7 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 7 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.58it/s]

Epoch 7/10 | Loss: 0.1173 | F1: 0.9242

Epoch 8 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 8 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.55it/s]

Epoch 8/10 | Loss: 0.1057 | F1: 0.9234
⚠️ No improvement (1/3)

Epoch 9 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 9 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.46it/s]

Epoch 9/10 | Loss: 0.0968 | F1: 0.9233
⚠️ No improvement (2/3)

Epoch 10 Training: 100%|██████████| 11834/11834 [07:59<00:00, 24.68it/s]
Epoch 10 Evaluating: 100%|██████████| 2959/2959 [00:39<00:00, 74.51it/s]

Epoch 10/10 | Loss: 0.0826 | F1: 0.9229
⚠️ No improvement (3/3)
🛑 Early stopping triggered
✅ BiGRU → Best F1-Macro: 0.9242
              precision    recall  f1-score   support

           1       0.93      0.93      0.93     11959
           2       0.96      0.96      0.96     18158
           3       0.90      0.92      0.91     25201
           4       0.86      0.92      0.89     13759
           5       0.95      0.94      0.95     19886
           6       0.97      0.98      0.97     27582
           7       0.99      0.99      0.99     24879
           8       0.89      0.86      0.88     27495
           9       0.96      0.97      0.96      9462
          10       0.83      0.77      0.80     10959

    accuracy                           0.93    189340
   macro avg       0.92      0.92      0.92    189340
weighted avg       0.93      0.93      0.93    189340


==================================================
⏳ Training TextRCNN...

Epoch 1 Training: 100%|██████████| 11834/11834 [03:37<00:00, 54.39it/s]
Epoch 1 Evaluating: 100%|██████████| 2959/2959 [00:19<00:00, 149.38it/s]

Epoch 1/10 | Loss: 0.4162 | F1: 0.8936

Epoch 2 Training: 100%|██████████| 11834/11834 [03:39<00:00, 53.92it/s]
Epoch 2 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 147.73it/s]

Epoch 2/10 | Loss: 0.2758 | F1: 0.9076

Epoch 3 Training: 100%|██████████| 11834/11834 [03:40<00:00, 53.65it/s]
Epoch 3 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 145.60it/s]

Epoch 3/10 | Loss: 0.2359 | F1: 0.9151

Epoch 4 Training: 100%|██████████| 11834/11834 [03:40<00:00, 53.62it/s]
Epoch 4 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 146.71it/s]

Epoch 4/10 | Loss: 0.1956 | F1: 0.9188

Epoch 5 Training: 100%|██████████| 11834/11834 [03:40<00:00, 53.55it/s]
Epoch 5 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 146.94it/s]

Epoch 5/10 | Loss: 0.1782 | F1: 0.9194

Epoch 6 Training: 100%|██████████| 11834/11834 [03:40<00:00, 53.76it/s]
Epoch 6 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 147.00it/s]

Epoch 6/10 | Loss: 0.1648 | F1: 0.9208

Epoch 7 Training: 100%|██████████| 11834/11834 [03:40<00:00, 53.71it/s]
Epoch 7 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 146.11it/s]

Epoch 7/10 | Loss: 0.1431 | F1: 0.9216

Epoch 8 Training: 100%|██████████| 11834/11834 [03:40<00:00, 53.72it/s]
Epoch 8 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 146.96it/s]

Epoch 8/10 | Loss: 0.1341 | F1: 0.9214
⚠️ No improvement (1/3)

Epoch 9 Training: 100%|██████████| 11834/11834 [03:40<00:00, 53.69it/s]
Epoch 9 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 146.55it/s]

Epoch 9/10 | Loss: 0.1266 | F1: 0.9209
⚠️ No improvement (2/3)

Epoch 10 Training: 100%|██████████| 11834/11834 [03:40<00:00, 53.76it/s]
Epoch 10 Evaluating: 100%|██████████| 2959/2959 [00:20<00:00, 146.04it/s]

Epoch 10/10 | Loss: 0.1145 | F1: 0.9209
⚠️ No improvement (3/3)
🛑 Early stopping triggered
✅ TextRCNN → Best F1-Macro: 0.9216
              precision    recall  f1-score   support

           1       0.92      0.93      0.93     11959
           2       0.95      0.96      0.96     18158
           3       0.90      0.91      0.91     25201
           4       0.88      0.89      0.89     13759
           5       0.94      0.95      0.94     19886
           6       0.97      0.97      0.97     27582
           7       0.99      0.99      0.99     24879
           8       0.88      0.87      0.87     27495
           9       0.96      0.97      0.96      9462
          10       0.81      0.79      0.80     10959

    accuracy                           0.93    189340
   macro avg       0.92      0.92      0.92    189340
weighted avg       0.93      0.93      0.93    189340


==================================================
⏳ Training TextCNN...

Epoch 1 Training: 100%|██████████| 11834/11834 [02:14<00:00, 87.99it/s]
Epoch 1 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 302.83it/s]

Epoch 1/10 | Loss: 0.5282 | F1: 0.8829

Epoch 2 Training: 100%|██████████| 11834/11834 [02:13<00:00, 88.59it/s]
Epoch 2 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 308.10it/s]

Epoch 2/10 | Loss: 0.3654 | F1: 0.8931

Epoch 3 Training: 100%|██████████| 11834/11834 [02:13<00:00, 88.45it/s]
Epoch 3 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 309.28it/s]

Epoch 3/10 | Loss: 0.3289 | F1: 0.9014

Epoch 4 Training: 100%|██████████| 11834/11834 [02:14<00:00, 88.24it/s]
Epoch 4 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 301.06it/s]

Epoch 4/10 | Loss: 0.2815 | F1: 0.9054

Epoch 5 Training: 100%|██████████| 11834/11834 [02:13<00:00, 88.39it/s]
Epoch 5 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 303.20it/s]

Epoch 5/10 | Loss: 0.2641 | F1: 0.9084

Epoch 6 Training: 100%|██████████| 11834/11834 [02:13<00:00, 88.43it/s]
Epoch 6 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 306.49it/s]

Epoch 6/10 | Loss: 0.2524 | F1: 0.9088

Epoch 7 Training: 100%|██████████| 11834/11834 [02:13<00:00, 88.49it/s]
Epoch 7 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 305.80it/s]

Epoch 7/10 | Loss: 0.2314 | F1: 0.9117

Epoch 8 Training: 100%|██████████| 11834/11834 [02:13<00:00, 88.52it/s]
Epoch 8 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 305.75it/s]

Epoch 8/10 | Loss: 0.2228 | F1: 0.9113
⚠️ No improvement (1/3)

Epoch 9 Training: 100%|██████████| 11834/11834 [02:13<00:00, 88.56it/s]
Epoch 9 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 306.86it/s]

Epoch 9/10 | Loss: 0.2166 | F1: 0.9122

Epoch 10 Training: 100%|██████████| 11834/11834 [02:14<00:00, 88.13it/s]
Epoch 10 Evaluating: 100%|██████████| 2959/2959 [00:09<00:00, 306.21it/s]

Epoch 10/10 | Loss: 0.2058 | F1: 0.9127
✅ TextCNN → Best F1-Macro: 0.9127
              precision    recall  f1-score   support

           1       0.92      0.92      0.92     11959
           2       0.94      0.95      0.95     18158
           3       0.90      0.89      0.90     25201
           4       0.88      0.87      0.88     13759
           5       0.94      0.94      0.94     19886
           6       0.97      0.96      0.97     27582
           7       0.99      0.99      0.99     24879
           8       0.85      0.87      0.86     27495
           9       0.95      0.96      0.96      9462
          10       0.79      0.76      0.77     10959

    accuracy                           0.92    189340
   macro avg       0.91      0.91      0.91    189340
weighted avg       0.92      0.92      0.92    189340


Kết quả Deep Learning:
   Model          Nhóm  Precision  Recall  F1-Macro  Accuracy    AUC
   BiGRU Deep Learning     0.9243  0.9247    0.9242    0.9301 0.9961
TextRCNN Deep Learning     0.9212  0.9220    0.9216    0.9274 0.9959
 TextCNN Deep Learning     0.9132  0.9123    0.9127    0.9191 0.9941

# Performance Evaluation of Transformer-Based Models for Vietnamese News Classification

In [ ]:
# ===================== 1. IMPORT =====================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from scipy.special import softmax

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

# ===================== 2. DATA =====================
# df cần có: 'content', 'label'
X = df['content']
y = df['label']

# Encode label
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# ===================== 3. SPLIT DATA =====================
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded
)

X_dev, X_test, y_dev, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

# ===================== 4. METRICS =====================
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    probs = softmax(logits, axis=1)
    preds = np.argmax(probs, axis=1)

    acc = accuracy_score(labels, preds)
    precision = precision_score(labels, preds, average="macro", zero_division=0)
    recall = recall_score(labels, preds, average="macro", zero_division=0)
    f1 = f1_score(labels, preds, average="macro", zero_division=0)

    try:
        auc = roc_auc_score(labels, probs, multi_class="ovr")
    except:
        auc = 0.0

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "macro_f1": f1,
        "auc": auc
    }

# ===================== 5. MODEL LIST =====================
model_list = [
    "vinai/phobert-base",
    "xlm-roberta-base",
    "bert-base-multilingual-cased"
]

results_all = {}

# ===================== 6. TRAIN LOOP =====================
for model_name in model_list:
    print(f"\n===== TRAINING {model_name} =====")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    # Dataset
    train_dataset = Dataset.from_dict({"text": list(X_train), "label": list(y_train)})
    dev_dataset   = Dataset.from_dict({"text": list(X_dev),   "label": list(y_dev)})
    test_dataset  = Dataset.from_dict({"text": list(X_test),  "label": list(y_test)})

    # Tokenize
    def tokenize(example):
        return tokenizer(
            example["text"],
            truncation=True,
            padding="max_length",
            max_length=256
        )

    train_dataset = train_dataset.map(tokenize, batched=True)
    dev_dataset   = dev_dataset.map(tokenize, batched=True)
    test_dataset  = test_dataset.map(tokenize, batched=True)

    train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
    dev_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
    test_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

    # Model
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=len(le.classes_)
    )

    # Training config
    training_args = TrainingArguments(
        output_dir=f"./results_{model_name.replace('/', '_')}",
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        logging_dir="./logs",
        report_to="none"
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=dev_dataset,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics
    )

    # Train
    trainer.train()

    # Evaluate
    result = trainer.evaluate(test_dataset)
    results_all[model_name] = result

# ===================== 7. FINAL RESULT =====================
print("\n===== FINAL RESULTS =====")
for model_name, res in results_all.items():
    print(f"\n{model_name}")
    print({
        "Accuracy": round(res["eval_accuracy"], 4),
        "Precision": round(res["eval_precision"], 4),
        "Recall": round(res["eval_recall"], 4),
        "Macro-F1": round(res["eval_macro_f1"], 4),
        "AUC": round(res["eval_auc"], 4)
    })

===== TRAINING vinai/phobert-base =====

Map:   0%|          | 0/662687 [00:00<?, ? examples/s]

Map:   0%|          | 0/142004 [00:00<?, ? examples/s]

Map:   0%|          | 0/142005 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.decoder.bias            | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
roberta.pooler.dense.weight     | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
roberta.pooler.dense.bias       | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.decoder.weight          | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

TypeError: Trainer.__init__() got an unexpected keyword argument 'tokenizer'

In [ ]:
# ===================== 1. IMPORT =====================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.calibration import CalibratedClassifierCV
from sklearn.base import clone

# ===================== 2. DATA =====================
X = df['content']
y = df['label']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print(f"Train: {len(X_train):,} | Test: {len(X_test):,}")
print(f"Số class: {len(le.classes_)}")

# ===================== 3. TF-IDF =====================
tfidf_full = TfidfVectorizer(ngram_range=(1,2), sublinear_tf=True, min_df=5)
tfidf_full.fit(X_train)

auto_max_features = min(int(len(tfidf_full.vocabulary_) * 0.6), 100_000)
del tfidf_full

tfidf = TfidfVectorizer(
    max_features=auto_max_features,
    ngram_range=(1,2),
    sublinear_tf=True,
    min_df=5,
    max_df=0.95
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

print(f"Vocab size: {len(tfidf.vocabulary_):,}")

# ===================== 4. MODELS =====================
ml_models = {

    "Naive Bayes":
        MultinomialNB(),

    "Logistic Regression":
        LogisticRegression(
            class_weight='balanced',
            max_iter=1000,
            random_state=42
        ),

    # LinearSVC được calibrate để có predict_proba
    "LinearSVC":
        CalibratedClassifierCV(
            LinearSVC(
                class_weight='balanced',
                C=1.0,
                max_iter=2000,
                random_state=42
            ),
            method='sigmoid',
            cv=3
        ),

    # đổi hinge → log_loss để có probability
    "SGDClassifier":
        SGDClassifier(
            loss='log_loss',
            class_weight='balanced',
            random_state=42,
            n_jobs=-1
        ),
}
# ===================== 5. LEARNING CURVE =====================
train_sizes = [0.01, 0.05, 0.1, 0.25, 0.5]
learning_results = []

for name, model in ml_models.items():

    print(f"\n🔥 Model: {name}")

    f1_list = []

    for frac in train_sizes:

        print(f"   ➤ Training với {int(frac*100)}% data")

        # tránh lỗi nếu data quá nhỏ
        frac_safe = max(frac, 0.02)

        X_sub, _, y_sub, _ = train_test_split(
            X_train,
            y_train,
            train_size=frac_safe,
            stratify=y_train,
            random_state=42
        )

        X_sub_tfidf = tfidf.transform(X_sub)

        # clone model để tránh overwrite
        model_clone = clone(model)

        model_clone.fit(X_sub_tfidf, y_sub)

        y_pred = model_clone.predict(X_test_tfidf)

        f1 = f1_score(y_test, y_pred, average="macro")
        f1_list.append(round(f1, 4))

    print("F1-macro list:", f1_list)

    learning_results.append({
        "Model": name,
        "Train_Sizes": train_sizes,
        "F1_List": f1_list
    })

# ===================== 6. RESULT =====================
df_learning = pd.DataFrame(learning_results)

print("\n"+"="*60)
print("LEARNING CURVE RESULT")
print("="*60)
print(df_learning.to_string(index=False))

# ===================== 7. SAVE =====================
df_learning.to_csv("learning_curve.csv", index=False)

print("\n✅ Saved learning_curve.csv")

# ===================== 8. PLOT =====================
import matplotlib.pyplot as plt

for _, row in df_learning.iterrows():
    plt.plot(
        [x*100 for x in row["Train_Sizes"]],
        row["F1_List"],
        marker='o',
        label=row["Model"]
    )

plt.xlabel("Training Data (%)")
plt.ylabel("Macro F1")
plt.title("Learning Curve")
plt.legend()
plt.grid()
plt.show()

Train: 757,356 | Test: 189,340
Số class: 10

In [ ]:
# ==================== IMPORT ====================
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset

from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer
from peft import PeftModel

from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score


# ==================== DATASET ====================
class NewsDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = int(self.labels[idx])

        encoding = self.tokenizer(
            text,
            truncation=True,
            max_length=self.max_len
        )

        encoding["labels"] = label
        return encoding


# ==================== CHỌN MODEL (QUAN TRỌNG) ====================
base_model_name = "vinai/phobert-base-v2"   # nếu sai → đổi xlm / mbert

tokenizer = AutoTokenizer.from_pretrained(base_model_name, use_fast=False)

test_dataset = NewsDataset(
    test_df['content'].tolist(),
    test_labels,
    tokenizer
)


# ==================== LOAD MODEL ====================
base_model = AutoModelForSequenceClassification.from_pretrained(
    base_model_name,
    num_labels=len(set(test_labels))
)

model = PeftModel.from_pretrained(
    base_model,
    "/content/results/checkpoint-62500"
)


from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    data_collator=data_collator   # 🔥 QUAN TRỌNG
)
predictions = trainer.predict(test_dataset)

y_pred = predictions.predictions.argmax(axis=-1)
y_true = predictions.label_ids


# ==================== METRICS ====================
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average='macro', zero_division=0
)

acc = accuracy_score(y_true, y_pred)

try:
    probs = F.softmax(torch.tensor(predictions.predictions), dim=1).numpy()
    auc = roc_auc_score(y_true, probs, multi_class='ovr')
except:
    auc = 0.0


print("\n===== FINAL RESULTS =====")
print(f"Accuracy   : {acc*100:.2f}")
print(f"Precision  : {precision*100:.2f}")
print(f"Recall     : {recall*100:.2f}")
print(f"Macro-F1   : {f1*100:.2f}")
print(f"AUC        : {auc*100:.2f}")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

===== FINAL RESULTS =====
Accuracy   : 87.67
Precision  : 86.10
Recall     : 87.98
Macro-F1   : 86.87
AUC        : 99.01